global_max_intensity = 10

[dolphin]
debug = true

[mode]
name      = "action"
intensity = 1
action = "SHIELD"
do_while = false

[players.1]
output_mode = "shock"

[players.2]
output_mode = "disabled"

